### ISSUE TITLE
Primer evento

### ISSUE THREAD

**Issue by delaguilaluis** [nodeschool/guatemala#2]
¡Buscamos mentores voluntarios para nuestro primer evento! 😄 
La idea es que enseñemos, desde cero, a quienes tengan interés en aprender JavaScript. Esto incluye a personas sin experiencia previa en programación.

El evento será el próximo miércoles 18 a las 18:30 en Chamba Coworking.

Los **requisitos** son los siguientes:
1. Haber completado el workshopper de [javascripting](https://www.github.com/sethvincent/javascripting) (cualquier [workshopper](https://nodeschool.io/#workshopper-list) adicional es un plus 💯 )
2. Leer el wiki [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices)
3. Leer nuestro [Código de conducta](https://github.com/nodeschool/guatemala/blob/master/codeofconduct.md)
4. Presentarse a la reunión de mentores(as), a realizarse media hora antes del evento

Comenten en este issue si están interesados y, ¡gracias por su apoyo! 👋 

Información del evento:

- Gitter: https://gitter.im/nodeschool/guatemala
- Evento en FB: https://www.facebook.com/events/463707850690979/
- Tweet de invitación al evento: https://twitter.com/nodeschoolgt/status/916405814998343681 

Mentores:
- @omarvides 
- @learnercys 
- @albizures 
- @gepser 
- @aleknaui
- @riktothepast

**Comment by wvides** [comment]
Estoy interesado en participar o/

**Comment by learnercys** [comment]
Interesado en participar :)

**Comment by ottogiron** [comment]
Por favos agregarme

**Comment by aleknaui** [comment]
Estoy interesada :)

**Comment by delaguilaluis** [comment]
@omarvides @learnercys @ottogiron @aleknaui ya los apunté. ¡Muchas gracias! :')

**Comment by riktothepast** [comment]
\o, si aun se puede :)

**Comment by gepser** [comment]
¿Qué fecha es el evento?

**Comment by delaguilaluis** [comment]
>El evento será el próximo miércoles 18 a las 18:30 en Chamba Coworking.

**Comment by albizures** [comment]
hey, yo tambien estoy interesado! ✌️

**Comment by delaguilaluis** [comment]
😄  Yo te apunto, Jose. ¿Está bien si uso tu foto de GitHub para el listado de mentores en la página?

**Comment by albizures** [comment]
Si, está bien @delaguilaluis

**Comment by delaguilaluis** [comment]
@omarvides @learnercys @albizures @gepser @aleknaui @riktothepast serán los mentores del evento. Por favor revisen si ya cumplieron con todos los **requisitos** mencionados arriba y nos vemos el miércoles a las 18:00. Empezaremos la reunión de mentores puntualmente, pues solo tenemos 30 mins. antes del evento.

Para cualquier duda, sugerencia o anuncio, por favor creen un issue nuevo.

¡Gracias! 😄
